apiVersion: v1
data:
  MYSQL_PASSWORD: TllPV1UqIzpDTVMteEcyPQ==
  SECRET_KEY: R1luI1hQNVI7Lm8qY0JUUyhkJmFtcDttWnc1OVc1Qkh3UDApLEY=
kind: Secret
metadata:
  creationTimestamp: "2019-09-12T03:34:16Z"
  name: webplatform-secret
  namespace: dev
  resourceVersion: "3744024"
  selfLink: /api/v1/namespaces/dev/secrets/webplatform-secret
  uid: 32b9ff40-d50e-11e9-9007-42010a8001b4
type: Opaque
